import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:google_fonts/google_fonts.dart';

final InputDecorationTheme customInputDecorationTheme = InputDecorationTheme(
  filled: true,
  fillColor: Colors.transparent, // Update as needed
  contentPadding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
  errorStyle: const TextStyle(fontSize: 9, fontWeight: FontWeight.w700),
  prefixStyle: const TextStyle(color: Colors.green),
  enabledBorder: OutlineInputBorder(
    borderRadius: BorderRadius.circular(8),
    borderSide: const BorderSide(color: Colors.grey),
  ),
  focusedBorder: OutlineInputBorder(
    borderRadius: BorderRadius.circular(8),
    borderSide: const BorderSide(color: Colors.green),
  ),
  focusedErrorBorder: OutlineInputBorder(
    borderRadius: BorderRadius.circular(8),
    borderSide: const BorderSide(color: Colors.red),
  ),
  errorBorder: OutlineInputBorder(
    borderRadius: BorderRadius.circular(8),
    borderSide: const BorderSide(color: Colors.red),
  ),
  floatingLabelStyle: const TextStyle(color: Colors.green),
  labelStyle: const TextStyle(fontSize: 11),
);

final ThemeData lightTheme = FlexColorScheme.light(
  scheme: FlexScheme.bigStone,

  surfaceMode: FlexSurfaceMode.highScaffoldLowSurfacesVariantDialog,
  blendLevel: 3,
  appBarOpacity: 0.1,
  appBarElevation: 1.0,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    defaultRadius: 13.0,
    filledButtonRadius: 34.0,
    elevatedButtonRadius: 34.0,
    outlinedButtonRadius: 34.0,
    outlinedButtonBorderWidth: 0.5,
    outlinedButtonPressedBorderWidth: 5.0,
    inputDecoratorBorderType: FlexInputBorderType.underline,
    fabUseShape: true,
    fabRadius: 25.0,
    cardRadius: 15.0,
    popupMenuRadius: 9.0,
    popupMenuElevation: 6.0,
    popupMenuOpacity: 0.91,
    dialogElevation: 18.0,
    dialogRadius: 50.0,
    datePickerDialogRadius: 33.0,
    timePickerDialogRadius: 50.0,
    timePickerElementRadius: 48.0,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 18,
    snackBarElevation: 17,
    appBarScrolledUnderElevation: 6.5,
    tabBarIndicatorWeight: 1.5,
    tabBarIndicatorTopRadius: 7,
    drawerRadius: 36.0,
    drawerElevation: 11.0,
    drawerWidth: 282.0,
    drawerIndicatorWidth: 500.0,
    drawerIndicatorRadius: 34.0,
    bottomSheetRadius: 30.0,
    bottomSheetElevation: 15.0,
    bottomSheetModalElevation: 18.0,
    bottomNavigationBarOpacity: 0.91,
    bottomNavigationBarElevation: 10.0,
    menuBarRadius: 10.0,
    menuBarElevation: 2.0,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  fontFamily: GoogleFonts.roboto().fontFamily,
).toTheme.copyWith(
      // Apply custom decoration theme
      inputDecorationTheme: customInputDecorationTheme,
    );

final ThemeData darkTheme = FlexColorScheme.dark(
  scheme: FlexScheme.bigStone,
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffoldVariantDialog,
  blendLevel: 3,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    defaultRadius: 13.0,
    filledButtonRadius: 34.0,
    elevatedButtonRadius: 34.0,
    outlinedButtonRadius: 34.0,
    outlinedButtonBorderWidth: 0.5,
    outlinedButtonPressedBorderWidth: 5.0,
    inputDecoratorBorderType: FlexInputBorderType.underline,
    fabUseShape: true,
    fabRadius: 25.0,
    cardRadius: 11.0,
    popupMenuRadius: 9.0,
    popupMenuElevation: 6.0,
    popupMenuOpacity: 0.91,
    dialogElevation: 18.0,
    dialogRadius: 50.0,
    datePickerDialogRadius: 33.0,
    timePickerDialogRadius: 50.0,
    timePickerElementRadius: 48.0,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 18,
    snackBarElevation: 17,
    tabBarIndicatorWeight: 1.5,
    tabBarIndicatorTopRadius: 7,
    drawerRadius: 36.0,
    drawerElevation: 11.0,
    drawerWidth: 282.0,
    drawerIndicatorWidth: 500.0,
    drawerIndicatorRadius: 34.0,
    bottomSheetRadius: 30.0,
    bottomSheetElevation: 15.0,
    bottomSheetModalElevation: 18.0,
    bottomNavigationBarOpacity: 0.91,
    bottomNavigationBarElevation: 10.0,
    menuBarRadius: 10.0,
    menuBarElevation: 2.0,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  fontFamily: GoogleFonts.roboto().fontFamily,
).toTheme.copyWith(
      // Apply custom decoration theme
      inputDecorationTheme: customInputDecorationTheme,
    );
